docs: ReadmeにER図の追加
yaJI02/OshiGoodsGallery pull request #4
Opened 2023-12-14 16:23 UTC by yaJI02

ReadmeにER図を追加しました。

[https://github.com/yaJI02/OshiGoodsGallery/blob/README/ERD.drawio.png](url)

### 補足
- TagsとMerchandise_tags、Content_tags、Favorite_point_tagsはポリモーフィック関連を定義する想定です。
  `Tag belongs_to :taggable, polymorphic: true`
  `MerchandiseTag has_one :tags, as: :taggable`
  `ContentTag has_one :tags, as: :taggable`
  `FavoritePointTag has_one :tags, as: :taggable`

- Postsのtypeにてグッズ投稿なのかショールーム投稿なのかを指定します。
  また、グッズ投稿の場合のみstatusにて「購入済・予約・検討中」を保存します。

- Profilesのdisplay_tag_typeにてタグの表示を「全て表示、地雷タグは非表示、お気に入りタグのみ表示」から選択してもらいます。
  また、display_ng_tagにて自分の設定した地雷タグ（NG_tags）を他の人に表示するかどうかを選択してもらいます。

- Post_stampはいいね機能を定義しています。
  あらかじめ「いいね、かわいい、かっこいい」などのスタンプで使用できるタグをenumで設定しておき、それを保存します。

2023-12-15 03:44 UTC, Tsuchiya2 commented
提出するURLはこちらにしてください。
その上で、ER図をコメント欄にURLではなく画像が表示される形での提出をお願いいたします。

2023-12-16 01:44 UTC, ooooose commented
ご提出ありがとうございます。
以下何点か気になりましたのでご確認・修正をお願いいたします。
テーブル数が多いため現状気づいた点のみ以下列挙しております。

- テーブルごとの関係性が正しいかについて整理をお願いします。
テーブルごとを繋ぐ矢印の種類が正しいか確認をお願いします。みたところ1対多で良い箇所も多対多で記載している箇所が複数あるように思います。
1対多なのか、中間テーブルを挟んでも多対多の矢印であっているかなど改めて整理をお願いいたします。
- いくつかのテーブルはまとめられると思いますので、整理をお願いします。
例えば、tags関連のテーブルではタグの種類ごとにテーブルを作っていますが、こちらtagsテーブルにカラムを追加することで解消しないでしょうか？
テーブル数は多すぎても管理が大変なので、まとめられる部分はまとめたほうがいいと思います。

2023-12-18 07:58 UTC, yaJI02 commented
ご確認ありがとうございました。

## 修正したER図
[![Image from Gyazo](https://i.gyazo.com/4cdd3e945105a6363fa9010dcb5ac144.png)](https://gyazo.com/4cdd3e945105a6363fa9010dcb5ac144)

・中間テーブルを挟んでいるものについて、１対多のリレーションへ変更しました。
・Tagについて、ポリモーフィック関連ではなくtypeカラムを用意することで種類を区別するように変更しました。

ご確認のほどよろしくお願いします。

2023-12-18 11:10 UTC, tarakish requested changes
修正確認しました。
リレーションの矢印は問題なさそうです👍
以下追加のコメントです！

---

- Tags
  - 種類を区別するのはよいですが、typeという名前はSTI（単一テーブル継承）のための予約語なので、それを意図していない場合は別の名前に変えておきましょう。
- Posts
  - bodyはstring型になっていますが、押しのグッズの説明などで文字数が足りそうかどうか少し気になりました。考慮済みでしたら問題ありませんが、一度ご確認をお願いします。
- Post_commentsとCommentsを分けている理由はありますか？
- Placeテーブルはどのような値が入り、投稿画面でどのように利用するかのイメージを説明いただけますでしょうか？
- 細かいですが、テーブル名はスネークケースかキャメルケースで統一しましょう！

2023-12-18 11:11 UTC, busitora commented
命名をメインにレビューしますね!

- timestamp は記載するか否か統一するといいと思います!

## profile

- sns_account は、どのSNSのURL? が格納されるのでしょうか? sns_account だと広義になってしまうので、もうすこし具体に落とすといいとおもいます。 例: x_account_url / instagram_account etc
-  display_ng_tag から、 booleanは連想しにくいので、  is_dislay_tag 等で、 カラムから boolとわかるようにし、ngという命名にしないほうが個人的には好きです (ng_tag まで修正することになるのであれば、変更に関してはおまかせしますよ!)
-  post_id に、 one/best/post が入るのが ??  となりました

##  tags

- カラム名に関して、 type は予約語なので使用できないはずなので別の命名考えるといいですね。 see: https://railsguides.jp/active_record_basics.html#%E3%82%B9%E3%82%AD%E3%83%BC%E3%83%9E%E3%81%AE%E3%83%AB%E3%83%BC%E3%83%AB

## post

- cost は、 何のコストかを明記したほうがいいと思います。 
- type について、上記と同様です
- display_comment も、 同じくboolであるかどうか分かるようにするといいですね!

2023-12-18 12:28 UTC, yaJI02 commented
tarakishさん、busitoraさんご確認ありがとうございました。

## 修正したER図
[![Image from Gyazo](https://i.gyazo.com/cf31d8190cbdb2ac8cc5823284d66909.png)](https://gyazo.com/cf31d8190cbdb2ac8cc5823284d66909)

- テーブル名をスネークケースに統一しました。

- timestampは記載しないに統一しました。

- テーブル名を変更しました。
（旧）NG_tags　（正）dislike_tags

- post_comments中間テーブルを削除し、commentsテーブルに直接post_idを保持させる形に変更しました。

- カラムを変更しました。
  - postsテーブル
    - bodyの型をstrからtextへ変更
    - bought_atの方をtimestampからdateへ変更
    - カラム名の変更
  （旧）cost　（正）purchase_cost
  （旧）type　（正）post_type
  （旧）status　（正）purchase_status
  （旧）display_comment　（正）is_display_comment

  - tagsテーブル
     - カラム名の変更
  （旧）type　（正）tag_type

  - profilesテーブル
     - カラム名の変更
  （旧）display_ng_tag　（正）is_dislay_dislike_tag

## その他ご指摘についての回答

- Placeテーブルはどのような値が入り、投稿画面でどのように利用するか
placeテーブルには購入場所の名称を入力してもらい、ユニークにすることで同じ内容を保存しないようにします。
投稿画面で購入場所を入力した際、同じ内容のカラムがすでに存在する場合にオートコンプリート機能で入力候補が表示されるようにします。

- sns_accountについて
この項目については特にアプリ内では使用せず、プロフィールに何かしらのアカウントを表記したい人が自由に入力する欄としているため、あえて広義なままにしています。

- post_id のone/best/postの記載について
profilesに自分のお気に入り投稿を保存できるようにしたかったためpost_idを保持しているのですが、何のためのpost_idなのか分かりにくいかなと思ってメモとして（one best post）と記載していました。不適切なため削除しました。

ご確認のほどよろしくお願いします。

2023-12-18 12:56 UTC, tarakish reviewed
修正確認しました。概ね問題なさそうです。
追加で一点、
> placeテーブルには購入場所の名称を入力してもらい、ユニークにすることで同じ内容を保存しないようにします。
投稿画面で購入場所を入力した際、同じ内容のカラムがすでに存在する場合にオートコンプリート機能で入力候補が表示されるようにします。

こちらのplaceテーブルですが、一つの投稿に複数のplaceが紐づくというイメージであっていますか？

2023-12-18 14:17 UTC, yaJI02 commented
tarakishさん

早速の確認ありがとうございます。
はい、一つの postが複数のplaceを持つこともあるという想定です。
よろしくお願いします。

2023-12-19 01:38 UTC, Tsuchiya2 commented
概ね良いかと思います。LGTMです。

2023-12-19 02:06 UTC, merged